#!/command/with-contenv sh

if [ ! -d /prosody/ssl ]; then
	mkdir -p /prosody/ssl
fi

if [ ! -f /prosody/ssl/default.crt ]; then
	/usr/bin/openssl req -nodes -newkey rsa:4096 -keyout /prosody/ssl/default.key -out /prosody/ssl/default.csr -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=default"
	/usr/bin/openssl x509 -req -days 365 -in /prosody/ssl/default.csr -signkey /prosody/ssl/default.key -out /prosody/ssl/default.crt
fi

/usr/bin/prosodyctl --root cert import /prosody/ssl

exit 0
