#!/usr/bin/with-contenv sh

if [ ! -L /data/web/config.php ]; then
	echo "[PHPBB FINISH] Saving existing config.."

	mv /data/web/config.php /phpbb/config.php

	ln -s /phpbb/config.php /data/web/config.php
fi

if [ ! -L /data/web/files ]; then
	echo "[PHPBB FINISH] Saving existing files.."

        mv /data/web/files /phpbb/files

        ln -s /phpbb/files /data/web/files
fi

if [ ! -L /data/web/ext ]; then
	echo "[PHPBB FINISH] Saving existing ext.."

        mv /data/web/ext /phpbb/ext

        ln -s /phpbb/ext /data/web/ext
fi

if [ ! -L /data/web/language ]; then
	echo "[PHPBB FINISH] Saving existing language.."

        mv /data/web/language /phpbb/language

        ln -s /phpbb/language /data/web/language
fi

if [ ! -L /data/web/store ]; then
	echo "[PHPBB FINISH] Saving existing store.."

        mv /data/web/store /phpbb/store

        ln -s /phpbb/store /data/web/store
fi

if [ ! -L /data/web/styles ]; then
	echo "[PHPBB FINISH] Saving existing styles.."

        mv /data/web/styles /phpbb/styles

        ln -s /phpbb/styles /data/web/styles
fi

if [ ! -L /data/web/images/avatars/upload ]; then
	echo "[PHPBB FINISH] Saving existing uploaded avatars.."

        mv /data/web/images/avatars/upload /phpbb/avatars_upload

        ln -s /phpbb/avatars_upload /data/web/images/avatars/upload

fi

exit 0
