#!/command/with-contenv sh

if [ ! -d /openfire/conf ]; then
	mv /app/openfire/conf /openfire/conf
	ln -s /openfire/conf /app/openfire/conf
fi

if [ -d /app/openfire/embedded-db ] && [ ! -d /openfire/embedded-db ]; then
	mv /app/openfire/embedded-db /openfire/embedded-db
	ln -s /openfire/embedded-db /app/openfire/embedded-db
fi

if [ ! -d /openfire/resources/security ]; then
	mkdir -p /openfire/resources
	mv /app/openfire/resources/security /openfire/resources/security
	ln -s /openfire/resources/security /app/openfire/resources/security
fi

if [ ! -d /openfire/plugins ]; then
	mv /app/openfire/plugins /openfire/plugins
	ln -s /openfire/plugins /app/openfire/plugins
fi

exit 0
