#!/command/with-contenv sh

if [ -d /openfire/conf ]; then
	if [ ! -L /app/openfire/conf ]; then
		rm -fr /app/openfire/conf
		ln -s /openfire/conf /app/openfire/conf
	fi
fi

if [ -d /openfire/embedded-db ]; then
	if [ ! -L /app/openfire/embedded-db ]; then
		rm -fr /app/openfire/embedded-db
		ln -s /openfire/embedded-db /app/openfire/embedded-db
	fi
fi

if [ -d /openfire/resources/security ]; then
	if [ ! -L /app/openfire/resources/security ]; then
		rm -fr /app/openfire/resources/security
		ln -s /openfire/resources/security /app/openfire/resources/security
	fi
fi

if [ -d /openfire/plugins ]; then
	if [ ! -L /app/openfire/plugins ]; then
		rm -fr /app/openfire/plugins
		ln -s /openfire/plugins /app/openfire/plugins
	fi
fi

exit 0
