#!/usr/bin/with-contenv sh

if [ ! -d /openfire/conf ]; then
	cp -rp /app/openfire/conf /openfire/conf
	rm -fr /app/openfire/conf
	ln -s /openfire/conf /app/openfire/conf
elif [ ! -L /app/openfire/conf]; then
	 /app/openfire/conf
	ln -s /openfire/conf /app/openfire/conf
fi

if [ -d /openfire/conf ]; then
	fi

if [ -d /openfire/embedded-db ]; then
	ln -s /openfire/embedded-db /app/openfire/embedded-db
fi

exit 0
