#!/command/with-contenv bash

echo "Initializing the container..."

test -z "${MYSQL_PORT_3306_TCP_ADDR}" && echo "Can not run without MySQL link!" && exit 1
test -z "${MYSQL_PORT_3306_TCP_PORT}" && echo "Can not run without MySQL link!" && exit 1

/usr/sbin/postconf "myhostname = ${HOSTNAME}"

if [ -f /data/conf/postfix/transport ]; then
	/usr/sbin/postmap /data/conf/postfix/transport
	/usr/sbin/postconf "transport_maps=mysql:/etc/postfix/virtual/mysql-virtual-transports.cf, hash:/data/conf/postfix/transport"
else
	/usr/sbin/postconf "transport_maps=mysql:/etc/postfix/virtual/mysql-virtual-transports.cf"
fi

echo ${HOSTNAME} > /etc/mailname

for file in /etc/postfix/header_checks.dist \
  /etc/postfix/virtual/*.cf.dist \
  /etc/dovecot/dovecot-sql.conf.ext.dist \
  /etc/dovecot/conf.d/90-plugin.conf.dist
do
  /usr/bin/gucci ${file} > $(dirname ${file})/$(basename $file .dist)
done

# /usr/bin/gucci /etc/dovecot/conf.d/90-plugin.conf.dist > /etc/dovecot/conf.d/90-plugin.conf

# Create files if they aren't created
if [ ! -f /etc/aliases ]; then
	touch /etc/aliases
fi

/usr/bin/newaliases

exit 0
