#!/usr/bin/with-contenv sh

if [ ! -L /data/web/config.php ]; then
	echo "[PHPBB FINISH] Saving existing config.."

	mv /data/web/config.php /phpbb/config.php

	ln -s /phpbb/config.php /data/web/config.php
fi

if [ ! -L /data/web/files ]; then
	echo "[PHPBB FINISH] Saving existing files.."

        mv /data/web/files /phpbb/files

        ln -s /phpbb/files /data/web/files
fi

if [ ! -L /data/web/ext ]; then
	echo "[PHPBB FINISH] Saving existing ext.."

        mv /data/web/ext /phpbb/ext

        ln -s /phpbb/ext /data/web/ext
fi

if [ ! -L /data/web/language ]; then
	echo "[PHPBB FINISH] Saving existing language.."

        mv /data/web/language /phpbb/language

        ln -s /phpbb/language /data/web/language
fi

exit 0
