#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
DOCKERFILE="$(basename $(dirname $(dirname $(readlink -f $0))))/Dockerfile"

set -x

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg DOCKERFILE="$DOCKERFILE" \
             -t $IMAGE_NAME .
