#!/usr/bin/with-contenv sh

# SSL setup !
if [ -f /data/ssl/ssl.pem ]; then
    postconf 'smtpd_tls_key_file=/data/ssl/ssl.pem'
    postconf 'smtpd_tls_cert_file=/data/ssl/ssl.pem'

    sed -i '/^ssl_cert =.*/d' /etc/dovecot/conf.d/10-ssl.conf
    sed -i '/^ssl_key =.*/d' /etc/dovecot/conf.d/10-ssl.conf

    cat >> /etc/dovecot/conf.d/10-ssl.conf <<< 'ssl_cert = </data/ssl/ssl.pem'
    cat >> /etc/dovecot/conf.d/10-ssl.conf <<< 'ssl_key = </data/ssl/ssl.pem'
elif [ -f /data/ssl/ssl.key ] && [ -f /data/ssl/ssl.crt ]; then
    postconf 'smtpd_tls_key_file=/data/ssl/ssl.key'
    postconf 'smtpd_tls_cert_file=/data/ssl/ssl.crt'

    sed -i '/^ssl_cert =.*/d' /etc/dovecot/conf.d/10-ssl.conf
    sed -i '/^ssl_key =.*/d' /etc/dovecot/conf.d/10-ssl.conf

    cat >> /etc/dovecot/conf.d/10-ssl.conf <<< 'ssl_cert = </data/ssl/ssl.key'
    cat >> /etc/dovecot/conf.d/10-ssl.conf <<< 'ssl_key = </data/ssl/ssl.crt'
fi

chown vmail:vmail /etc/dovecot/sieve -R

exit 0
