#!/usr/bin/with-contenv sh

if [ ! -d /data/assp ]; then
	mkdir -p /data/assp
fi

if [ ! -d /data/assp/database ]; then
	mv /usr/share/assp/database /data/assp/database
	ln -s /data/assp/database /usr/share/assp/database
elif [ ! -L /usr/share/assp/database ]; then
	rm -fr /usr/share/assp/database
	ln -s /data/assp/database /usr/share/assp/database
fi

if [ ! -d /data/assp/dkim ]; then
        mv /usr/share/assp/dkim /data/assp/dkim
        ln -s /data/assp/dkim /usr/share/assp/dkim
elif [ ! -L /usr/share/assp/dkim ]; then
        rm -fr /usr/share/assp/dkim
        ln -s /data/assp/dkim /usr/share/assp/dkim
fi

if [ -f /data/assp/assp.cfg ]; then
	rm /usr/share/assp/assp.cfg
	ln -s /data/assp/assp.cfg /usr/share/assp/assp.cfg
else
	if [ ! -f /usr/share/assp/assp.cfg ]; then
		cp /usr/share/assp/assp.cfg.defaults /data/assp/assp.cfg
		ln -s /data/assp/assp.cfg /usr/share/assp/assp.cfg
	else
		mv /usr/share/assp/assp.cfg /data/assp/assp.cfg
		ln -s /data/assp/assp.cfg /usr/share/assp/assp.cfg
	fi
fi

if [ ! -d /data/assp/files ]; then
        mv /usr/share/assp/files /data/assp/files
        ln -s /data/assp/files /usr/share/assp/files
elif [ ! -L /usr/share/assp/files ]; then
        rm -fr /usr/share/assp/files
        ln -s /data/assp/files /usr/share/assp/files
fi

if [ ! -d /data/assp/quarantine ]; then
        mv /usr/share/assp/quarantine /data/assp/quarantine
        ln -s /data/assp/quarantine /usr/share/assp/quarantine
elif [ ! -L /usr/share/assp/quarantine ]; then
        rm -fr /usr/share/assp/quarantine
        ln -s /data/assp/quarantine /usr/share/assp/quarantine
fi

chown vmail:vmail /etc/dovecot/sieve -R

exit 0
