#!/usr/bin/with-contenv bash

set -e

function stop {
    echo Stopping postfix
    /usr/sbin/postfix stop

    exit
}

function reload {
    echo Reloading postfix

    /usr/sbin/postfix reload
}

function start {
    # Run new aliases
    # start postfix
    /usr/sbin/postfix -c /etc/postfix start
    # avoid exiting
}

trap stop SIGINT SIGTERM SIGKILL
trap reload SIGHUP

start

tail -f /dev/null
