#!/usr/bin/with-contenv sh

if [ ! -z $DOCKER_ENDPOINT ]; then
	exec /app/docker-gen -config /app/docker-gen.cfg -endpoint $DOCKER_ENDPOINT
fi

exec /app/docker-gen -config /app/docker-gen.cfg -endpoint unix:///tmp/docker.sock
