#!/usr/bin/with-contenv bash

cat > /app/djigzo/conf/database/hibernate.mysql.connection.xml <<EOF
<!-- connection settings for MySQL (MariaDB) database -->

<property name="hibernate.connection.url">jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/${DJIGZO_MYSQL_DATABASE}</property>
<property name="hibernate.connection.username">${DJIGZO_MYSQL_USER}</property>
<property name="hibernate.connection.password">${DJIGZO_MYSQL_PASSWORD}</property>
EOF

exit 0
