#!/usr/bin/with-contenv bash

cat > /app/djigzo/conf/james/SAR-INF/smtp_transport_config.xml <<EOF
<!-- 
    The SMTP client settings used to inject mail back into Postfix
    
    Note: if you change this port from the default (10026) you should also change the content_filter
    setting in the Postfix main.cf config file.     
-->

<!-- Although normally multiple addresses are implemented through proper -->
<!-- DNS configuration, the RemoteDelivery mail does allow specifying -->
<!-- multiple gateway elements, each of which may also have a port -->
<!-- e.g., mygateway:2525 -->
<!-- the gatewayPort element is used as a default -->
<gateway> ${MAIL_CALLBACK_IP} </gateway>
<gatewayPort> ${MAIL_CALLBACK_PORT} </gatewayPort>
EOF

exit 0
