name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: alpine-base
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-base:latest
          context: alpine-base
      -
        name: alpine-nginx-php5 
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php5
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-php5:latest
          context: alpine-nginx-php5
      -
        name: alpine-nginx-php7
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php7
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-php7:latest
          context: alpine-nginx-php7
      -
        name: alpine-nginx-php8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php8
          context: alpine-nginx-php8
      -
        name: alpine-nginx-static
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:static
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-static:latest
          context: alpine-nginx-static
      -
        name: alpine-virtualmail-fuglu
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-virtualmail:fuglu
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-virtualmail:latest
          context: alpine-virtualmail-fuglu
      -
        name: alpine-nginx-nextcloud
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-nextcloud:latest
          context: alpine-nginx-nextcloud
      -
        name: alpine-haproxy
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-haproxy:latest
          context: alpine-haproxy

