name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: alpine-base
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-base:latest
          context: alpine-base
      -
        name: alpine-base-3.5
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-base:3.5
          context: alpine-base-3.5
      -
        name: alpine-base-3.8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-base:3.8
          context: alpine-base-3.8
      -
        name: alpine-base-3.8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-base:3.15
          context: alpine-base-3.15
      -
        name: alpine-nginx-php5 
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php5
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-php5:latest
          context: alpine-nginx-php5
      -
        name: alpine-nginx-php7
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php7
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-php7:latest
          context: alpine-nginx-php7
      -
        name: alpine-nginx-php8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:php8
          context: alpine-nginx-php8
      -
        name: alpine-nginx-static
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:static
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-static:latest
          context: alpine-nginx-static
      -
        name: alpine-virtualmail-fuglu
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-virtualmail:fuglu
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-virtualmail:latest
          context: alpine-virtualmail-fuglu
      -
        name: alpine-nginx-nextcloud
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-nextcloud:latest
          context: alpine-nginx-nextcloud
      -
        name: alpine-haproxy
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-haproxy:latest
          context: alpine-haproxy
      -
        name: alpine-aptly
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-aptly:latest
          context: alpine-aptly
      -
        name: alpine-netdata
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-netdata:latest
          context: alpine-netdata
      -
        name: alpine-nginx-freshrss
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-freshrss:latest
          context: alpine-nginx-freshrss
      -
        name: alpine-grimd
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-grimd:latest
          context: alpine-grimd
      -
        name: alpine-nginx-matomo
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-matomo:latest
          context: alpine-nginx-matomo
      -
        name: alpine-nginx-nextcloud
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-nextcloud:latest
          context: alpine-nginx-nextcloud
      -
        name: alpine-nginx-rainloop
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-rainloop:php5
          context: alpine-nginx-rainloop
      -
        name: alpine-nginx-rainloop-php7
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-rainloop:php7
          context: alpine-nginx-rainloop-php7
      -
        name: alpine-nginx-rainloop-php8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-rainloop:php8
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-rainloop:latest
          context: alpine-nginx-rainloop-php8
      -
        name: alpine-nginx-snappymail-php8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-snappymail:php8
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-snappymail:latest
          context: alpine-nginx-snappymail-php8
      -
        name: alpine-nginx-wordpress-php7
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-wordpress:php7
          context: alpine-nginx-wordpress-php7
      -
        name: alpine-nginx-wordpress-php8
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-wordpress:php8
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-wordpress:latest
          context: alpine-nginx-wordpress-php8
      -
        name: alpine-prosody
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-prosody:latest
          context: alpine-prosody
      -
        name: alpine-posty-api
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-posty-api:latest
          context: alpine-posty-api
      -
        name: alpine-posty-webui
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-posty-webui:latest
          context: alpine-posty-webui
      -
        name: alpine-mumble
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-mumble:latest
          context: alpine-mumble
      -
        name: alpine-teamspeak3
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-teamspeak3:latest
          context: alpine-teamspeak3
      -
        name: alpine-weechat
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-weechat:latest
          context: alpine-weechat
      -
        name: alpine-newsboat
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-newsboat:latest
          context: alpine-newsboat
      -
        name: alpine-nginx-phpbb
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-phpbb:php5
          context: alpine-nginx-phpbb
      -
        name: alpine-nginx-phpbb-php7
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-phpbb:php7
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-nginx-phpbb:latest
          context: alpine-nginx-phpbb-php7
      -
        name: alpine-spiderfoot
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-spiderfoot:latest
          context: alpine-spiderfoot
      -
        name: alpine-musicbot
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-musicbot:latest
          context: alpine-musicbot
      -
        name: alpine-b3
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/alpine-b3:latest
          context: alpine-bigbrother-b3

